name: Build

on: [push]

jobs:
  test:
    strategy:
      matrix:
        node: ["12.x"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install yarn
        run: npm install -g yarn

      - name: Set output of cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Node dependency cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ matrix.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Bootstrap dependencies
        run: yarn run bootstrap

      - name: Build
        run: yarn run build

      - name: Build Types
        run: yarn run build:types
